enum AcledRegionCode {
  'Western Africa' = 1,
  'Middle Africa' = 2,
  'Eastern Africa' = 3,
  'Southern Africa' = 4,
  'Northern Africa' = 5,
  'South Asia' = 7,
  'Southeast Asia' = 9,
  'Middle East' = 11,
  'Europe' = 12,
  'Caucasus and Central Asia' = 13,
  'Central America' = 14,
  'South America' = 15,
  'Caribbean' = 16,
  'East Asia' = 17,
  'North America' = 18,
  'Oceania' = 19,
  'Antarctica' = 20,
}
